import { MenuItem, BranchSettings, Coupon, Order } from './types';

export const INITIAL_BRANCH_SETTINGS: BranchSettings = {
  name: 'مطعم كشري هند - الفرع الرئيسي',
  siteName: 'كشري هند',
  whatsappNumber: '201012345678',
  address: 'شارع الحجاز - مصر الجديدة / فرع وسط البلد',
  phone: '19876',
  isOpen: true,
  deliveryFee: 15,
  minOrderAmount: 30,
  estimatedDeliveryTime: '25 - 35 دقيقة',
  acceptingOrders: true,
  closingMessage: 'نعتذر، المطعم مغلق حالياً. يسعدنا استقبال طلباتكم في أوقات العمل من 10 صباحاً حتى 2 صباحاً.',
  heroCardImage: 'https://images.unsplash.com/photo-1541518763669-27fef04b14da?auto=format&fit=crop&q=80&w=800',
  heroCardBadge: 'الأكثر مبيعاً 🔥',
  heroCardTitle: 'كشري هند الخصوصي',
  heroCardDesc: 'حمص، عدس أصلي، تقلية مقرمشة، وصلصة هند المسبكة',
  heroCardPrice: '45',
};

export const INITIAL_COUPONS: Coupon[] = [
  {
    id: 'c1',
    code: 'HIND10',
    discountPercent: 10,
    minOrderAmount: 50,
    isActive: true,
  },
  {
    id: 'c2',
    code: 'KOSHARI20',
    discountPercent: 20,
    minOrderAmount: 100,
    isActive: true,
  },
  {
    id: 'c3',
    code: 'WELCOME',
    discountPercent: 15,
    minOrderAmount: 40,
    isActive: true,
  },
];

export const COMMON_ADDONS = [
  { id: 'a1', name: 'علبة دقة ثوم وخل', price: 5 },
  { id: 'a2', name: 'علبة صلصة طماطم زياده', price: 6 },
  { id: 'a3', name: 'علبة شطة زيتها حارة', price: 5 },
  { id: 'a4', name: 'باكيت تقلية بصل مقرمش', price: 7 },
  { id: 'a5', name: 'باكيت حمص مقرمش زياده', price: 7 },
  { id: 'a6', name: 'عيش توست محمص بالبهارات', price: 10 },
];

export const INITIAL_MENU: MenuItem[] = [
  {
    id: 'k1',
    name: 'كشري هند المخصوص (سوبر)',
    description: 'أرز بشعرية، مكرونة مشكلة، عدس بجبه، حمص، تقلية بصل ذهبية، مع دقة وصلصة هند الخاصة.',
    category: 'koshari',
    basePrice: 35,
    image: 'https://images.unsplash.com/photo-1541518763669-27fef04b14da?auto=format&fit=crop&q=80&w=800',
    isAvailable: true,
    isPopular: true,
    sizes: [
      { id: 's1', name: 'فويل صغير', price: 25 },
      { id: 's2', name: 'علبة وسط', price: 35 },
      { id: 's3', name: 'علبة كبير سوبر', price: 45 },
      { id: 's4', name: 'طبق هند الملكي (ميجا)', price: 60 },
    ],
    availableAddons: COMMON_ADDONS,
  },
  {
    id: 'k2',
    name: 'كشري أطباق الفويل الساخنة',
    description: 'طبق كشري سخن ومسبك بالكامل في أطباق الفويل، يحافظ على السخونة والقرمشة.',
    category: 'koshari',
    basePrice: 30,
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&q=80&w=800',
    isAvailable: true,
    isPopular: false,
    sizes: [
      { id: 'f1', name: 'فويل وسط', price: 30 },
      { id: 'f2', name: 'فويل جامبو', price: 40 },
    ],
    availableAddons: COMMON_ADDONS,
  },
  {
    id: 'k3',
    name: 'كشري هند بدون مكرونة (دايت عدس وحمص)',
    description: 'طبق كشري غني بالعدس الأسمر والحمص المسبك والتقلية بدون مكرونة لراغبي الدايت.',
    category: 'koshari',
    basePrice: 32,
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&q=80&w=800',
    isAvailable: true,
    isNew: true,
    sizes: [
      { id: 'd1', name: 'وسط', price: 32 },
      { id: 'd2', name: 'كبير', price: 42 },
    ],
    availableAddons: COMMON_ADDONS,
  },
  {
    id: 't1',
    name: 'طاجن مكرونة باللحمة المفرومة',
    description: 'طاجن مكرونة فرن باللحم البلدي المفروم والصلصة المسبكة والبهارات الشرقية.',
    category: 'tajins',
    basePrice: 45,
    image: 'https://images.unsplash.com/photo-1621996346565-e3def616403c?auto=format&fit=crop&q=80&w=800',
    isAvailable: true,
    isPopular: true,
    sizes: [
      { id: 't1_1', name: 'طاجن وسط', price: 45 },
      { id: 't1_2', name: 'طاجن سوبر كبير', price: 60 },
    ],
    availableAddons: COMMON_ADDONS,
  },
  {
    id: 't2',
    name: 'طاجن مكرونة بالفراخ والموزاريلا',
    description: 'قطع دجاج متبلة بالفرن مع المكرونة والصلصة الحارة وجبنة موزاريلا سايحة.',
    category: 'tajins',
    basePrice: 50,
    image: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&q=80&w=800',
    isAvailable: true,
    isPopular: true,
    isSpicy: true,
    sizes: [
      { id: 't2_1', name: 'طاجن وسط', price: 50 },
      { id: 't2_2', name: 'طاجن جامبو', price: 68 },
    ],
    availableAddons: COMMON_ADDONS,
  },
  {
    id: 't3',
    name: 'طاجن كبدة إسكندراني بالشرائح',
    description: 'كبدة بلدي بالثوم والفلفل الأخضر الحار مع مكرونة فرن مسبكة.',
    category: 'tajins',
    basePrice: 48,
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&q=80&w=800',
    isAvailable: true,
    isSpicy: true,
    sizes: [
      { id: 't3_1', name: 'وسط', price: 48 },
      { id: 't3_2', name: 'كبير', price: 62 },
    ],
    availableAddons: COMMON_ADDONS,
  },
  {
    id: 's1_dish',
    name: 'وجبة سبيشال هند (كشري + طاجن + حلو)',
    description: 'علبة كشري سوبر + طاجن لحمة مفرومة صغير + طبق أرز باللبن + كوكاكولا.',
    category: 'special',
    basePrice: 95,
    image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&q=80&w=800',
    isAvailable: true,
    isPopular: true,
    availableAddons: COMMON_ADDONS,
  },
  {
    id: 'f1_meal',
    name: 'وجبة العائلة الكبيرة (4 أفراد)',
    description: 'سرفيس كشري عائلي عملاق + 2 طاجن فرخ ولحمة + 4 أكياس تقلية ودقة + 4 أرز باللبن + لتر كانز.',
    category: 'family',
    basePrice: 280,
    image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&q=80&w=800',
    isAvailable: true,
    availableAddons: COMMON_ADDONS,
  },
  {
    id: 'ad1',
    name: 'عيش محمص بالبهارات الكمونية',
    description: 'مثلثات خبز شامي مقرمش بالزيت والكمون والملح الثومي.',
    category: 'addons',
    basePrice: 12,
    image: 'https://images.unsplash.com/photo-1509722747041-616f39b57569?auto=format&fit=crop&q=80&w=800',
    isAvailable: true,
  },
  {
    id: 'ad2',
    name: 'سلطة خضراء بلدي طازجة',
    description: 'طماطم، خيار، جرجير، بصل، ليمون ودقة خل وثوم.',
    category: 'addons',
    basePrice: 12,
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&q=80&w=800',
    isAvailable: true,
  },
  {
    id: 'd1_sweet',
    name: 'أرز باللبن والمكسرات بالفرن',
    description: 'أرز بلبن بلدي طازج مخبوز بالفرن مع القشطة والمكسرات المحمصة.',
    category: 'desserts',
    basePrice: 20,
    image: 'https://images.unsplash.com/photo-1579372786545-d24232daf58c?auto=format&fit=crop&q=80&w=800',
    isAvailable: true,
    isPopular: true,
  },
  {
    id: 'd2_sweet',
    name: 'قنبلة كشري هند (أرز بلبن + فواكه + بسبوسة + قشطة)',
    description: 'طبق الحلو الأشهر! طبق أرز باللبن، قطع مانجو وموز، قطعة بسبوسة، وقشطة وسيروب.',
    category: 'desserts',
    basePrice: 38,
    image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&q=80&w=800',
    isAvailable: true,
    isPopular: true,
    isNew: true,
  },
  {
    id: 'd3_sweet',
    name: 'طاجن أم علي بالقشطة والمكسرات',
    description: 'أم علي سخنة بالحليب البلدي والسمن البلدي والقشطة والمكسرات.',
    category: 'desserts',
    basePrice: 28,
    image: 'https://images.unsplash.com/photo-1587314168485-3236d6710814?auto=format&fit=crop&q=80&w=800',
    isAvailable: true,
  },
  {
    id: 'b1',
    name: 'مشروب حمص الشام الحار (الرمزيات)',
    description: 'كوب حمص شام سخن بالدقة والليمون والشطة الحارة.',
    category: 'beverages',
    basePrice: 18,
    image: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&q=80&w=800',
    isAvailable: true,
    isSpicy: true,
  },
  {
    id: 'b2',
    name: 'مشروب كانز بارد (كوكاكولا / سبرايت / فانتا)',
    description: 'عبوة كانز مثلجة اختيارية.',
    category: 'beverages',
    basePrice: 15,
    image: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&q=80&w=800',
    isAvailable: true,
  },
];

export const INITIAL_SEED_ORDERS: Order[] = [
  {
    id: 'KH-1082',
    createdAt: new Date(Date.now() - 1000 * 60 * 12).toISOString(), // 12 mins ago
    items: [
      {
        cartItemId: 'seed-1',
        menuItem: INITIAL_MENU[0],
        selectedSize: INITIAL_MENU[0].sizes![1], // علبة وسط (35)
        selectedAddons: [COMMON_ADDONS[0], COMMON_ADDONS[3]], // دقة + تقلية
        quantity: 2,
        notes: 'صلصة زياده وسخنة جداً لو سمحت',
        totalPrice: (35 + 5 + 7) * 2, // 94
      },
      {
        cartItemId: 'seed-2',
        menuItem: INITIAL_MENU[3], // طاجن لحمة
        selectedSize: INITIAL_MENU[3].sizes![0],
        selectedAddons: [],
        quantity: 1,
        totalPrice: 45,
      },
      {
        cartItemId: 'seed-3',
        menuItem: INITIAL_MENU[11], // قنبلة هند
        selectedAddons: [],
        quantity: 1,
        totalPrice: 38,
      },
    ],
    subtotal: 177,
    deliveryFee: 15,
    discount: 10,
    total: 182,
    status: 'preparing',
    orderType: 'delivery',
    paymentMethod: 'cash',
    customer: {
      name: 'أحمد محمود العبد',
      phone: '01012345678',
      address: 'شارع الأهرام - عمارة 14 - الشقة 3 - الكوربة مصر الجديدة',
      buildingFloor: 'الدور الثالث',
      notes: 'الاتصال عند الوصول للباب',
    },
    estimatedTimeMinutes: 25,
  },
  {
    id: 'KH-1081',
    createdAt: new Date(Date.now() - 1000 * 60 * 35).toISOString(), // 35 mins ago
    items: [
      {
        cartItemId: 'seed-4',
        menuItem: INITIAL_MENU[1], // فويل
        selectedSize: INITIAL_MENU[1].sizes![1],
        selectedAddons: [],
        quantity: 3,
        totalPrice: 120,
      },
      {
        cartItemId: 'seed-5',
        menuItem: INITIAL_MENU[10], // أرز باللبن
        selectedAddons: [],
        quantity: 3,
        totalPrice: 60,
      },
    ],
    subtotal: 180,
    deliveryFee: 15,
    discount: 0,
    total: 195,
    status: 'delivering',
    orderType: 'delivery',
    paymentMethod: 'vodafone_cash',
    customer: {
      name: 'سارة شريف',
      phone: '01198765432',
      address: 'شارع طلعت حرب - وسط البلد القصر العيني',
      notes: 'تم الدفع فودافون كاش',
    },
    estimatedTimeMinutes: 30,
  },
  {
    id: 'KH-1080',
    createdAt: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
    items: [
      {
        cartItemId: 'seed-6',
        menuItem: INITIAL_MENU[7], // وجبة عائلية
        selectedAddons: [COMMON_ADDONS[0], COMMON_ADDONS[1]],
        quantity: 1,
        totalPrice: 291,
      },
    ],
    subtotal: 291,
    deliveryFee: 0,
    discount: 30,
    total: 261,
    status: 'completed',
    orderType: 'pickup',
    paymentMethod: 'card',
    customer: {
      name: 'مهندس مصطفى كامل',
      phone: '01234567890',
      address: 'استلام من الفرع - وسط البلد',
    },
    estimatedTimeMinutes: 15,
  },
];
